name: Test Hydrogen-Lattice on Push

on:
  push:
    paths:
      - 'hydrogen-lattice/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: pip install -r hydrogen-lattice/tests/requirements.txt
      working-directory: ./
    - name: Run tests
      run: pytest
      working-directory: hydrogen-lattice
